- name: printed varibles in playlevel
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: printed varibles in playlevel
    ansible.builtin.debug:
     msg: "i am learning course is {{COURSE}} trainer is {{TRAINER}} and duration is {{DURATION}}"
