- name: printed varibles from inventory file
  hosts: mongodb
  tasks:
  - name: printed varibles from inventory file
    ansible.builtin.debug:
     msg: "i am learning course is {{COURSE}} trainer is {{TRAINER}} duration is {{DURATION}}"